# Header
menu:
  Home: /
  Archives: /archives
  About: /about
  Codeforces: http://codeforces.com/profile/changyuheng
  GitHub: https://github.com/changyuheng
  LinkedIn: http://tw.linkedin.com/pub/yu-heng-chang/56/583/6b8/
  Facebook: https://www.facebook.com/mr.changyuheng
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: left
widgets:
- recent_posts
- tag

# Miscellaneous
google_analytics: UA-44162683-1
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
